name: controlling execution

on:
  workflow_dispatch:
    inputs:
      unit_tests_pass:
        type: boolean
        default: false
        description: "unit tests will pass or not"

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: build and lint
        run: echo "this is a build and lint step, we just print we are not on a true app config"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: run unit tests
        run: |
          echo "this is a unit test step"
          if [ "${{ inputs.unit_tests_pass }}" = "false" ]; then
            exit 1
          fi

  deploy-noprod:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to non-production
        run: echo "this is a deploy to non-production step"

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: run end-to-end tests
        run: echo "this is an end-to-end test step"

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - e2e-tests
    steps:
      - name: deploy to production
        run: echo "this is a deploy to production step"


    