name: workflow events

on: 
    push : 
        branches:
            - main
                 
        paths-ignore:
            - "/src/docs/**"  #ceci pour ignorer les changements dans le dossier docs par exemple 
    pull_request :
    schedule: 
        - cron: '0 0 * * *'  #cron expression can be found here: https://crontab.guru/
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "this is will execute an event which is ${{github.event_name}}"