name: workflow event filters and types

on: 
  pull_request: 
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - "react-app/my-app/node_modules/**"  

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "this is will execute an event which is ${{ github.event_name }}"
